name: FORCE BUILD APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: FORCE INSTALL
        run: |
          npm install --force
          npm install -g eas-cli
      
      - name: FORCE BUILD
        run: |
          npx expo install
          eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      
      - name: UPLOAD APK
        uses: actions/upload-artifact@v4
        with:
          name: app.apk
          path: '*.apk'
